classdef fuzzySystemRandomTest < matlab.unittest.TestCase
% Parameterized random tests for fuzzySystem.solve_inverse over multiple
% operations, matrix sizes and numeric precisions.

    properties (TestParameter)
        operation = struct( ...
            'maxmin',          'maxmin', ...
            'minmax',          'minmax', ...
            'maxprod',         'maxprod', ...
            'goguen',          'goguen', ...
            'godel',           'godel', ...
            'lukasiewicz',     'lukasiewicz', ...
            'maxepsilon',      'maxepsilon', ...
            'maxlukasiewicz',  'maxlukasiewicz' ...
        );

        aSize = struct( ...
            's2x2',   [2 2], ...
            's3x3',   [3 3], ...
            's2x5',   [2 5] ...
        );

        precision = struct( ...
            'p1',  1, ...
            'p4',  4 ...
        );

        % Final stability contract: exercise every operation/size/precision
        % combination with 50 deterministic, reproducible random examples.
        repetition = num2cell(1:50);
    end

    methods (Test)
        function testRandomExample(testCase, operation, aSize, precision, repetition)
            seed = 100000 * repetition + 1000 * aSize(1) + ...
                100 * aSize(2) + 10 * precision + sum(double(operation));
            previousRng = rng(seed, 'twister');
            restoreRng = onCleanup(@() rng(previousRng)); %#ok<NASGU>
            A = fuzzyMatrix(round(rand(aSize), precision));
            X = fuzzyMatrix(round(rand(aSize(2), 1), precision));
            B = feval(operation, A, X);
            s = fuzzySystem(operation, A, B, [], true);

            logMessage = sprintf([ ...
                'Random fuzzySystem test failed.\n' ...
                'operation = %s\n' ...
                'seed = %d, repetition = %d\n' ...
                'size(A) = [%d %d], precision = %d\n' ...
                'A = %s\n' ...
                'X = %s\n' ...
                'B = %s\n'], ...
                operation, seed, repetition, aSize(1), aSize(2), precision, ...
                mat2str(double(A)), mat2str(double(X)), mat2str(double(B)) ...
            );

            verifyNoException(testCase, @() s.solve_inverse(), logMessage);
            testCase.verifyTrue(isfield(s.x, 'exist') && s.x.exist, ...
                ['No solution found for a system that must have one.\n' logMessage]);
            testCase.verifyTrue(isstruct(s.x) && isfield(s.x,'low') && isfield(s.x,'gr'), ...
                ['Solver output must contain struct s.x with fields low and gr.' newline logMessage]);
            testCase.verifyTrue(isfield(s.x, 'help_inclusive') && ...
                isfield(s.x, 'low_inclusive') && isfield(s.x, 'gr_inclusive'), ...
                ['Solver output must expose the standardized boundary masks.' newline logMessage]);
            testCase.verifySize(s.x.help_inclusive, size(s.x.help), logMessage);
            testCase.verifySize(s.x.low_inclusive, size(s.x.low), logMessage);
            testCase.verifySize(s.x.gr_inclusive, size(s.x.gr), logMessage);
            testCase.verifyTrue(all(s.x.help_inclusive(:)) && ...
                all(s.x.low_inclusive(:)) && all(s.x.gr_inclusive(:)), ...
                ['Equation boundaries must all be closed.' newline logMessage]);
            testCase.verifyTrue(size(s.x.gr,2) >= 1 && size(s.x.low,2) >= 1 && size(s.x.gr,1) == size(s.x.low,1), ...
                ['Solutions dimentions mismatch.\n' logMessage]);
            testCase.verifyTrue(all(all(s.x.low <= s.x.gr)), ...
                ['All lower solutions must be <= upper solutions.\n' logMessage]);

            validCombinationCount = 0;
            for i = 1:size(s.x.low, 2)
                for j = 1:size(s.x.gr, 2)
                    if all(s.x.low(:, i) <= X & X <= s.x.gr(:, j))
                        validCombinationCount = validCombinationCount + 1;
                    end
                end
            end
            testCase.verifyGreaterThanOrEqual(validCombinationCount, 1, ...
                ['The original X must be in at least one interval solution.\n' logMessage]);

            for i = 1:size(s.x.low, 2)
                val = feval(operation, A, s.x.low(:, i));
                testCase.verifyEqual( ...
                    val, B, ...
                    'AbsTol', 1e-10, ...
                    ['A*low(:,i) must equal B for all lower solutions.\n' logMessage]);
            end

            for i = 1:size(s.x.gr, 2)
                val = feval(operation, A, s.x.gr(:, i));
                testCase.verifyEqual( ...
                    val, B, ...
                    'AbsTol', 1e-10, ...
                    ['A*gr(:,i) must equal B for all upper solutions.\n' logMessage]);
            end

            for i = 1:size(s.x.low,2)
                for j = 1:size(s.x.low,2)
                    if i == j, continue; end
                    vi = s.x.low(:,i);
                    vj = s.x.low(:,j);
                    dominates = all(vi <= vj);
                    msg = sprintf(['Lower solution %d dominates %d; ' ...
                        'set of lower solutions should be minimal.\n%s'], ...
                        i, j, logMessage);
                    testCase.verifyFalse(dominates, msg);
                end
            end

            for i = 1:size(s.x.gr,2)
                for j = 1:size(s.x.gr,2)
                    if i == j, continue; end
                    vi = s.x.gr(:,i);
                    vj = s.x.gr(:,j);
                    dominates = all(vi >= vj);
                    msg = sprintf(['Upper solution %d dominates %d; ' ...
                        'set of upper solutions should be minimal.\n%s'], ...
                        i, j, logMessage);
                    testCase.verifyFalse(dominates, msg);
                end
            end
        end
    end
end
